export enum GEOLOCATION_ERROR {
    TIMEOUT = 'TIMEOUT',
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    POSITION_UNAVAILABLE = 'POSITION_UNAVAILABLE',
    GEOLOCATION_NOT_AVAILABLE = 'GEOLOCATION_NOT_AVAILABLE',
}
