export const PATHS = {
    REBIRTH_OUTCOMES: {
        GENE_ARTEFACT: '/img/rebirth/outcomes/gene-artefact.svg',
        GENESIS: '/img/rebirth/outcomes/genesis.svg',
        GLASSES: '/img/rebirth/outcomes/glasses.svg',
        PHOENIX: '/img/rebirth/outcomes/phoenix.svg',
        SUIT: '/img/rebirth/outcomes/suit.svg',
        CROWN: '/img/rebirth/outcomes/art_crown.svg',
        BUILT_BODY: '/img/rebirth/outcomes/art_builtbody.svg',
        SNAKE: '/img/rebirth/outcomes/art_snake.svg',
        ROBODUCK: '/img/rebirth/outcomes/art_roboduck.svg',
        KATANA: '/img/rebirth/outcomes/art_katana.svg',
        SCEPTER: '/img/rebirth/outcomes/art_scepter.svg',
        ART_FIRE_ARMOUR: '/img/rebirth/outcomes/art_fire_armour.svg',
        ART_FIRE_HELMET: '/img/rebirth/outcomes/art_fire_helmet.svg',
        ART_FIRE_SWORD: '/img/rebirth/outcomes/art_fire_sword.svg',
        ART_FIRE_TAIL: '/img/rebirth/outcomes/art_fire_tail.svg',
        ART_FIRE_SHIELD: '/img/rebirth/outcomes/art_fire_shield.svg',
        BEACH_S: '/img/rebirth/outcomes/beach_s.svg',
        BEACH_D: '/img/rebirth/outcomes/beach_d.svg',
        BEACH_R: '/img/rebirth/outcomes/beach_r.svg',
        BEACH_G: '/img/rebirth/outcomes/beach_g.svg',
        GENESIS_TURTLE: '/img/rebirth/outcomes/genesisturtle.png',
    },
    PLAY_AND_EARN: {
        WARS: '/metaverse/play-and-earn/wars.png',
        HUNT: '/metaverse/play-and-earn/hunt.png',
        WAVESLANDS: '/metaverse/play-and-earn/waveslands.png',
        ROUNDS: '/metaverse/play-and-earn/squid.png',
    },
};
